spring.datasource.url=jdbc:mysql://localhost:3306/course_spring_boot_practise
spring.datasource.username=root
spring.datasource.password=9491490888
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8080